---
- name: MongoDB Cluster RS Status Check
  hosts: servers
  # become: yes
  
  tasks:
    - name: Get MongoDB RS Status
      ansible.builtin.shell: mongosh --eval 'rs.status()' | grep -E 'set|state|uptime|ok|cluster|name'
      register: command_result_output

    - name: Display MongoDB RS Status
      debug:
        var: command_result_output.stdout_lines
