---
- name: Create MongoDB Backup
  hosts: host2
  become: yes

  tasks:
    - name: Update Package Cache
      apt:
        update_cache: yes

    - name: Install Required Packages
      apt:
        name:
          - zip
          - unzip
          - tar
        state: present

    - name: Create Backup Directory
      ansible.builtin.file:
        path: /home/backup
        state: directory

    - name: Copy Script File >> /home/mongodb_backup_bash_script.sh
      template:
        src: mongodb_backup_bash_script_conf.j2
        dest: /home/mongodb_backup_bash_script.sh
        mode: '0644'

    - name: Execute Shell Script >> /home/mongodb_backup_bash_script.sh
      shell: bash /home/mongodb_backup_bash_script.sh

    - name: Get MongoDB Backup Folder Status > /home
      ansible.builtin.shell: ls -anp /home/
      register: command_result_output

    - name: Display MongoDB Backup Status
      debug:
        var: command_result_output.stdout_lines

    - name: Display Message
      debug:
        msg: "Mongodb host: {{ ansible_default_ipv4.address }} >> Backup path: /home/ >> Backup script >> /home/mongodb_backup_bash_script.sh"
