---
- name: Create MongoDB Backup
  hosts: host2
  become: yes

  tasks:
    - name: Create Backup Directory
      ansible.builtin.file:
        path: /home/backup
        state: directory

    - name: Type 1 Backup - Run mongodump backup in folder > /home/backup
      ansible.builtin.shell: mongodump --out /home/backup

    - name: Type 2 Backup - Run mongodump backup archive file > /home/db.archive
      ansible.builtin.shell: mongodump --host=localhost --port=27017 --archive=/home/db.archive
