---
- name: Setup MongoDB Cluster
  hosts: servers
  become: yes
  
  vars:
    mongodb_version: "6.0"
    mongodb_data_dir: "/var/lib/mongodb"
    mongodb_log_dir: "/var/log/mongodb"
    mongodb_bind_ip: "0.0.0.0"
    mongodb_port: 27017
    mongodb_replica_set_name: "myreplica"

  tasks:
    - name: Set Hostname
      hostname:
        name: "{{ desired_hostname }}"

    - name: Update Package Cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Ubuntu"

    - name: Install Required Packages
      apt:
        name:
          - unzip
          - curl
          - wget
          - gnupg2
          - software-properties-common
          - apt-transport-https
          - ca-certificates
          - lsb-release
        state: present
      when: ansible_os_family == "Ubuntu"

    - name: Download MongoDB GPG Key
      # shell: wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | sudo apt-key add -
      shell: curl -fsSL https://www.mongodb.org/static/pgp/server-6.0.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/mongodb-6.gpg

    - name: Add MongoDB Repository
      # shell: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-5.0.list
      shell: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu $(lsb_release -cs)/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list

    - name: Update APT Package Cache
      apt:
        update_cache: yes

    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present
        update_cache: yes
      vars:
        mongodb_version: "{{ mongodb_version }}"
      when: ansible_os_family == "Ubuntu"

    - name: Start MongoDB Service
      service:
        name: mongod
        state: started
        enabled: yes

    - name: Run MongoDB Version Command
      command: mongod --version
      register: mongod_version_output

    - name: Display MongoDB Version
      debug:
        var: mongod_version_output.stdout_lines

    - name: Configure MongoDB
      template:
        src: mongodb.conf.j2
        dest: /etc/mongod.conf
      notify: Reload MongoDB

    - name: Initialize MongoDB Replica Set
      shell: |
        mongo --eval 'rs.initiate(
          {
            _id: "{{ mongodb_replica_set_name }}",
            members: [
              { _id: 0, host: "host1:{{ mongodb_port }}", priority: 2 },
              { _id: 1, host: "host2:{{ mongodb_port }}", priority: 1 },
              { _id: 2, host: "host3:{{ mongodb_port }}", arbiterOnly: true }
            ]
          }
        )'
      ignore_errors: yes

  handlers:
    - name: Reload MongoDB
      service:
        name: mongod
        state: reloaded
