---
- name: TEST
  hosts: servers
  become: yes
  
  tasks: 
    - name: Initialize MongoDB Replica Set
      ansible.builtin.shell: |
        mongosh --eval 'rs.initiate({ _id: "{{ mongodb_replica_set_name }}", members: [{ _id: 0, host: "host1:{{ mongodb_port }}", priority: 2 }, { _id: 1, host: "host2:{{ mongodb_port }}", priority: 1 }, { _id: 2, host: "host3:{{ mongodb_port }}", arbiterOnly: true }]})' > /dev/null 2>&1
      ignore_errors: yes
