---
- name: TEST
  hosts: servers
  become: yes
  
  vars:
    mongodb_version: "6.0"
    mongodb_data_dir: "/var/lib/mongodb"
    mongodb_log_dir: "/var/log/mongodb"
    mongodb_bind_ip: "0.0.0.0"
    mongodb_port: 27017
    mongodb_replica_set_name: "myreplica"

  tasks: 
    - name: Initialize MongoDB Replica Set
      ansible.builtin.shell: |
        mongosh --eval 'rs.initiate({ _id: "{{ mongodb_replica_set_name }}", members: [{ _id: 0, host: "host1:{{ mongodb_port }}", priority: 2 }, { _id: 1, host: "host2:{{ mongodb_port }}", priority: 1 }, { _id: 2, host: "host3:{{ mongodb_port }}", arbiterOnly: true }]})' > /dev/null 2>&1
      ignore_errors: yes
