---
- name: Remove lines with host1 from /etc/hosts file
  hosts: servers
  become: yes
  
  tasks:
    - name: Remove lines with host1 from /etc/hosts
      lineinfile:
        path: /etc/hosts
        state: absent
        regexp: ".*\\shost1\\s.*"

    - name: Remove lines with host2 from /etc/hosts
      lineinfile:
        path: /etc/hosts
        state: absent
        regexp: ".*\\shost2\\s.*"

    - name: Remove lines with host3 from /etc/hosts
      lineinfile:
        path: /etc/hosts
        state: absent
        regexp: ".*\\shost3\\s.*"

    - name: Add host1 entry to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ hostvars['host1'].ansible_default_ipv4.address }} host1"
        insertbefore: EOF

    - name: Add host2 entry to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ hostvars['host2'].ansible_default_ipv4.address }} host2"
        insertbefore: EOF

    - name: Add host3 entry to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ hostvars['host3'].ansible_default_ipv4.address }} host3"
        insertbefore: EOF
