---
- name: TEST
  hosts: servers
  become: yes
  
  vars:
    mongodb_version: "6.0"
    mongodb_data_dir: "/var/lib/mongodb"
    mongodb_log_dir: "/var/log/mongodb"
    mongodb_bind_ip: "0.0.0.0"
    mongodb_port: 27017
    mongodb_replica_set_name: "myreplica"

  tasks:
    - name: Initialize MongoDB Replica Set
      ansible.builtin.shell: bash /etc/mongodb.deploy.conf.sh
      register: command_result
      ignore_errors: yes

    - name: Check if the task had an error
      debug:
        msg: "Task completed with an error: {{ command_result.stderr }}"
      when: command_result.failed

    - name: Display the command's output
      debug:
        msg: "Command output: {{ command_result.stdout }}"
      when: not command_result.failed
      